# ----
# Site

title: SDG Wiki
url: "https://long-pig.cloudvent.net"
baseurl:
google_analytics_key:
show_full_navigation: true
excerpt_separator: "" 

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product documentation template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: SDG Wiki
  links:
    - https://github.com/CloudCannon/edition-jekyll-template

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true
  iotwiki:
    output: true
    permalink: /:path/
  cookies:
    output: true
    permalink: /cookies/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release


    scope:
      path: ""
      type: "cookies"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation


# -----------
# CloudCannon

types:
  - minor
  - major
